spring:
    application:
        name: boot-thymeleaf

    # DB 설정
    datasource:
        # driver-class-name: oracle.jdbc.driver.OracleDriver > 9i
        # driver-class-name: oracle.jdbc.OracleDriver
        # url: jdbc:oracle:thin:@localhost:1521/xe
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:oracle:thin:@localhost:1521/xe
        username: springboot
        password: java1234

    # 타임리프 캐시(사용안함) > 개발 시
    thymeleaf:
        cache: false


server:
    port: 8090

# XML Mapper Locations
mybatis:
    mapper-locations: classpath:/mapper/*.xml



















